import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Link from "next/link";
import styles from "@/styles/Home.module.scss";
import ConnectionDropdown from "./connectionDropdown";
import Head from "next/head";
import React, { useState, useEffect } from "react";

interface SidebarItem {
  Name: string;
  Path: string;
  Icon: string;
  New?: boolean;
  Updated?: boolean;
}

interface Menu {
  sidebarItems: SidebarItem[];
}

const Sidebar: React.FC = () => {
  const [menu, setMenu] = useState<Menu | null>(null);
  const [collapsed, setCollapsed] = useState(false);

  useEffect(() => {
    async function fetchData() {
      fetch("/menu.json")
      .then((response) => response.json())
      .then((data) => setMenu(data))
    }
    fetchData();
  }, []);

  const handleCollapse = () => {
    setCollapsed(!collapsed);
  };

  return (
    <nav className={`${styles["sidebar"]} ${collapsed ? styles.collapsed : styles.expanded}`}>
      <button className={`${styles["expandButton"]} ${collapsed ? styles.expandButtoncollapsed : ""}`} onClick={handleCollapse}>
        {collapsed ? <span className="material-symbols-outlined">arrow_right</span> : <span className="material-symbols-outlined">arrow_left</span>}
      </button>
      <ul>
        {menu?.sidebarItems.map((item, index: number) => (
          <li
            key={index}
            className={styles["sidebar__item"]}>
             <span className="material-symbols-outlined">{item.Icon}</span><a href={item.Path}>{item.Name}</a>
          </li>
        ))}
      </ul>
    </nav>
  );
};



// interface Menu {
//   topBar: { id: string; label: string; url: string }[];
//   sideMenu: { id: string; label: string; url: string }[];
//   sidebar: SidebarItem[];
// }

// function Sidebar() {
//   const [sidebarItems, setSidebarItems] = useState<SidebarItem[]>([]);
//   const [isExpanded, setIsExpanded] = useState(true);

//   useEffect(() => {
//     async function fetchMenu() {
//       const response = await fetch("/menu.json");
//       const data = await response.json();
//       setSidebarItems(data.sidebar);
//     }

//     fetchMenu();
//   }, []);

//   // Render the sidebar items
//   return (
//     <div
//       className={`${styles.sidebar} ${
//         isExpanded ? styles.expanded : styles.collapsed
//       }`}
//     >
//       <div className={styles.expandButtonContainer}>
//         <button
//           className={styles.expandButton}
//           onClick={() => setIsExpanded(!isExpanded)}
//         >
//           <span className={`material-symbols-outlined  ${styles.expandIcon}`}>
//             menu
//           </span>
//         </button>
//       </div>
//       {/* <nav> */}
//         <div className={styles.sidebar}>
//           {sidebarItems.map((item) => (
//             <div key={item.Name} className={styles.sidebar}>{item.Name}</div>
//           ))}
//         </div>
//       {/* </nav> */}
//     </div>
//   );
// }

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Next App</title>
        <style>{`
    :root {
      --bg-color: #0d1117;
    }
    body {
      background-color: var(--bg-color);
    }
  `}</style>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dog.png" />
      </Head>
      <div className={styles.main}>
        <div className={styles["topbar"]}>
          <div className={styles.logo}></div>
          <div className={styles["linksContainer"]}>
            <Link className={styles["links"]} href="/">
              Home
            </Link>
            <Link className={styles["links"]} href="/register">
              Register
            </Link>
            <Link className={styles["links"]} href="/propOptions">
              Prop Options
            </Link>
            <Link className={styles["links"]} href="/codeEditor">
              Code Editor
            </Link>
          </div>
          <Sidebar />
          <ConnectionDropdown jsonFileName="connections" label="Connections" />
        </div>
        <Component {...pageProps} />
      </div>
    </>
  );
}
