import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Link from "next/link";
import topBarStyles from "./TopBar.module.css";
import main from "@/styles/Home.module.css";
import ConnectionDropdown from "./connectionDropdown";
import Head from "next/head";
import homeStyles from "@/styles/Home.module.css";
// import './index.css'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Next App</title>
        <style>{`
    :root {
      --bg-color: #0d1117;
    }
    body {
      background-color: var(--bg-color);
    }
  `}</style>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dog.png" />
      </Head>
      <div className={main.main}>
        <div className={topBarStyles["topbar"]}>
          <div className={topBarStyles.logo}></div>
          <div className={topBarStyles["linksContainer"]}>
            <Link className={homeStyles["links"]} href="/">
              Home
            </Link>
            <Link className={homeStyles["links"]} href="/register">
              Register
            </Link>
            <Link className={homeStyles["links"]} href="/codeEditor">
              Code Editor
            </Link>
          </div>
            <ConnectionDropdown jsonFileName="connections" label="Connections" />
        </div>
        <Component {...pageProps} />
      </div>
    </>
  );
}
