import Head from "next/head"
import styles from "@/styles/Home.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <style>{`
          :root {
            --bg-color: #0d1117;
          }
          body {
            background-color: var(--bg-color);
          }
        `}</style>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dog.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}></div>
      </main>
    </>
  );
}
