import Head from "next/head";
import styles from "./Home.module.scss";
import React from "react";
import Grid from "./Grid";

const Home: React.FC = ({}) => (
  <>
    <Head>
      <title>Shakely API</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles["main"]}>
      <div key={"main"} style={{ position: "relative", zIndex: 0 }}>
        <Grid />
      </div>
    </main>
  </>
);

export default Home;
