import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Dropdown from "./dropdown";
import CodeEditor from "./codeEditor";
import TopBar from "./TopBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <style>{`
          :root {
            --bg-color: #0d1117;
          }
          body {
            background-color: var(--bg-color);
          }
        `}</style>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dog.png" />
      </Head>
      <main className={styles.main}>
        <TopBar />
        <CodeEditor />

        <div className={styles.grid}></div>
      </main>
    </>
  );
}
